### ISSUE TITLE
Recently error when Start local game

### ISSUE THREAD

**Issue by takaaptech** [TxN/VoxelLand#2]
Hi @TxN 
I am still following the update of VoxelLand and in recently update, I got this error:

```
UnityException: FindObjectsOfType can only be called from the main thread.
Constructors and field initializers will be executed from the loading thread when loading a scene.
Don't use this function in the constructor or field initializers, instead move initialization code to the Awake or Start function.
UnityEngine.Object.FindObjectOfType (System.Type type) (at /Users/bokken/buildslave/unity/build/Runtime/Export/Scripting/UnityEngineObject.bindings.cs:404)
SMGCore.ManualSingleton`1[T].get_Instance () (at Assets/LightGameCore/Scripts/GameSystems/ManualSingleton.cs:8)
Voxels.Networking.Serverside.UnityLandGenerator.RunGenRoutine () (at Assets/Scripts/Networking/Serverside/UnityLandGenerator.cs:25)
Voxels.Networking.Serverside.ServerLandGenerator.TryStartGeneration () (at Assets/Scripts/Networking/Serverside/ServerLandGenerator.cs:56)
Voxels.Networking.Serverside.ServerChunkManager.LoadGenWorldOrigin () (at Assets/Scripts/Networking/Serverside/ServerChunkManager.cs:400)
Voxels.Networking.Serverside.ServerChunkManager.PostLoad () (at Assets/Scripts/Networking/Serverside/ServerChunkManager.cs:81)
Voxels.Networking.ServerGameManager.PostLoad () (at Assets/Scripts/Networking/Serverside/ServerGameManager.cs:96)
Voxels.ServerThreadRunner.Run (Voxels.Networking.ServerGameManager server, System.Int32 tickTime, System.Int32 rareTickTime, System.Threading.CancellationTokenSource cancellationTokenSource) (at Assets/Scripts/ServerThreadRunner.cs:18)
Voxels.GameManager.<Start>b__23_0 () (at Assets/Scripts/GameManager.cs:81)
System.Threading.ThreadHelper.ThreadStart_Context (System.Object state) (at <695d1cc93cca45069c528c15c9fdd749>:0)
```

Could you please take a look? Thank you so much!

**Comment by TxN** [comment]
Hmm, that's strange, could you please check latest commit? I was sure that this singleton should be properly initialized at the moment, I've added some safety checks to make sure that Instance property of this singleton is initialized before staerting a server thread.

**Comment by takaaptech** [comment]
The first two run after git clone new project, we have a strange error like this:
```
A Native Collection has not been disposed, resulting in a memory leak. Enable Full StackTraces to get more details.
```
![image](https://user-images.githubusercontent.com/6276251/127947256-3d885487-fe3c-4f3a-ba40-5c5c7c72c969.png)

And then we still have the same error as above

![image](https://user-images.githubusercontent.com/6276251/127947488-3ca71bf2-b5bd-4f5a-aee5-2d9e17bed9ec.png)


I can confirm that I delete and git clone the latest commit

![image](https://user-images.githubusercontent.com/6276251/127947609-33c3b989-78f9-44b4-a81f-7d57d51dbd76.png)

Thank you so much

**Comment by TxN** [comment]
Oh, I've found what caused this issue, and I hope that I've fixed it. 
If not, try to comment line 399 in ServerChunkManager (Owner.AddToInitQueue(this) ). But I hope that won't be needed.

**Comment by takaaptech** [comment]
Hi @TxN 
OK take it easy and trying to fix it. Thank you so much for helping me!
I am trying to comment on the code at line 79 but we still have the same error

![image](https://user-images.githubusercontent.com/6276251/128002630-9fe7cb37-1320-4b17-a16d-2bf21ca23932.png)


Waiting for you new commit

**Comment by TxN** [comment]
Please update to the latest commit, I've made changes that probably should mitigate this error (and this method call is moved to another place, to line 399, this was made to fix another bug with server initialization)

**Comment by takaaptech** [comment]
Hi @TxN 
We still the error on the first time (git clone, open the game, open HeadlessRunner scene, press Start local game )

![image](https://user-images.githubusercontent.com/6276251/128108656-8314b965-fa83-4f30-bf78-fbb5835b7c35.png)

After that, we can now enter the game, thank you so much!
